# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

notifications:
  email:
    - hansune@me.com

branches:
  except:
    - gh-pages

install:
  - gem install xcpretty

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="ValueAnimator"
    - UPDATE_DOCS="true"

matrix:
  include:
    - osx_image: xcode14
      env: SCHEME="macOS"  SDK="macosx12.3"           DESTINATION="OS=12.6,arch=x86_64"                    SWIFT_VERSION="5.0" ACTION="test"
    - osx_image: xcode14
      env: SCHEME="iOS"    SDK="iphonesimulator"      DESTINATION="OS=16.0,name=iPhone 14"          SWIFT_VERSION="5.0" ACTION="test"
    - osx_image: xcode14
      env: SCHEME="tvOS"   SDK="appletvsimulator"     DESTINATION="OS=16.0,name=Apple TV 4K (at 1080p) (2nd generation)"       SWIFT_VERSION="5.0" ACTION="test"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    "$ACTION"
    -workspace "$FRAMEWORK_NAME.xcworkspace"
    -scheme "$FRAMEWORK_NAME-$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    SWIFT_VERSION=$SWIFT_VERSION

#after_success:
#  - bash <(curl -s https://codecov.io/bash) -J ValueAnimator
#  - test $TRAVIS_PULL_REQUEST == "false" &&
#    test $TRAVIS_BRANCH == "master" &&
#    test $UPDATE_DOCS == "true" &&
#    .scripts/update-gh-pages
